version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:
