name: Docker CI/CD

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true  # Only proceed if the pull request is merged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_TOKEN }}     

    - name: Set up Docker context
      run: docker context create my-context --docker "host=unix:///var/run/docker.sock"

    - name: Build and push Docker images
      run: |
        docker buildx build --push --platform linux/amd64,linux/arm64 \
        -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
        docker buildx build --push --platform linux/amd64,linux/arm64 \
        -t ${{ secrets.DOCKER_USERNAME }}/mysql-container:latest -f Dockerfile.mysql .

    - name: Deploy application
      run: |
        docker run --env-file .env -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        docker run -d -p 3306:3306 \
        --env-file .env \
        ${{ secrets.DOCKER_USERNAME }}/mysql-container:latest
